print(".......STRING ANALYSER.......")
sentence=input("Enter a sentence:")
print("original sentence:",sentence)
upper_case=(sentence.upper())
print("upper case:",upper_case)
lower_case=(sentence.lower())
print("lower case:",lower_case)
old=input("enter the word to replace:")
new=input("it is replace with:")
replaced_sentence=(sentence.replace(old,new))
print("replaced sentence:",replaced_sentence)
stripped_sentence=(sentence.strip())
print("stripped sentence:",stripped_sentence)
first_character=(sentence[0])
print("first character:",first_character)
print(sentence[-1])
print(sentence[:5])
print(sentence[5:])
print(sentence[::2])
print(sentence[::-1])
print(sentence.replace(" ",""))
print(len(sentence))

print("focus,practice,consistency is a key to sucess good job!")      
