student=["vani","pavi","surya","akash","janvi","harsha","fah","darsh"]
print("oroginal list:",student)
(student.append("rakshitha"))
print(student)
(student.insert(0,"deeku"))
print(student)
(student.remove("vani"))
print(student)
(student.pop(1))
print(student)
print(student.index("darsh"))
print(len(student))
print(student[:3])
print(student[-3:])
print(student)
print(sorted(student))
print("student:",student)
student.reverse()
print(student)
student.clear()
print(student)

